# Generated by Django 5.1.6 on 2025-03-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'text'), ('IMAGE', 'image')], default='TEXT', max_length=50),
        ),
    ]
