# Generated by Django 5.1.6 on 2025-03-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=50),
        ),
    ]
